---
extends: default

rules:
  # for some reason my github actions YAML trip this one but I don't understand why
  truthy: disable
  # 88 chars should be enough, but don't fail if a line is longer
  line-length: disable
  new-lines: disable
  # following rules added to prevent conflicts with Prettier:
  indentation: disable
  braces: disable
