---
Description: Generates a BigFix Task for the latest DockerDesktop
Identifier: com.github.bigfix.bigfix.DockerDesktop-Win64
Input:
  # Name: Short Name of the Software, No spaces, Example: "DBBrowserforSQLite"
  NAME: "DockerDesktop"
  # DisplayName: The start of the DisplayName key in the Windows Registry, Example: "DB Browser for SQLite"
  DisplayName: "Docker Desktop"
MinimumVersion: "2.3"
ParentRecipe: com.github.bigfix.download.DockerDesktop-Win64
Process:
  # `SharedUtilityMethods` must come first
  - Processor: com.github.jgstew.SharedProcessors/SharedUtilityMethods
  #- Processor: com.github.jgstew.SharedProcessors/FileExeVersionExtractor
  - Processor: com.github.jgstew.SharedProcessors/TemplateDictionaryAppend
    Arguments:
      dictionary_name: download_info
      append_key: file_name
      append_value: DockerDesktop.exe
  # `BigFixPrefetchItem` takes the hashes from `URLDownloaderPython`
  #   Then it assembles them into a BigFix Prefetch Statement or Block
  - Processor: com.github.jgstew.SharedProcessors/BigFixPrefetchItem
  - Processor: com.github.jgstew.SharedProcessors/BigFixSetupTemplateDictionary

  - Processor: URLDownloaderPython
    Arguments:
      filename: "%NAME%-icon.png"
      url: https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png
      COMPUTE_HASHES: False

  - Processor: com.github.jgstew.SharedProcessors/FileGetBase64

  - Processor: com.github.jgstew.SharedProcessors/TemplateDictionaryAppend
    Arguments:
      append_key: "icon_base64"
      append_value: "%file_base64%"
  # `BigFixSetupTemplateDictionary` creates a dictionary to fill out a bigix content template
  #   If `SourceReleaseDate` is not provided, it will be set to today
  #- Processor: com.github.jgstew.SharedProcessors/BigFixSetupTemplateDictionary
  # `TemplateDictionaryAppend` adds extra variables to the Template Dictionary
  #   This is only needed if the template uses extra variables
  - Processor: com.github.jgstew.SharedProcessors/TemplateDictionaryAppend
    Arguments:
      dictionary_name: template_dictionary
      append_key: "DisplayName"
      append_value: "%DisplayName%"
  - Processor: com.github.jgstew.SharedProcessors/TemplateDictionaryAppend
    Arguments:
      dictionary_name: template_dictionary
      append_key: file_name
      append_value: DockerDesktop.exe
  # `ContentFromTemplate` generates bigfix content from a mustache template file
  #   The file is filled out with variables from the Template Dictionary
  #   If variables are missing from the Template Dictionary, then that area will be blank
  - Processor: com.github.jgstew.SharedProcessors/ContentFromTemplate
    Arguments:
      template_file_path: "./Docker/%NAME%-Win64-Install_Update.bes.mustache"
      content_file_pathname: "%RECIPE_CACHE_DIR%/%NAME%.bes"
  # `BESImport` imports the generated BES content into a BigFix Server
  #   Which server and credentials are used is dictated by `~/.besapi.conf`
  - Processor: com.github.jgstew.SharedProcessors/BESImport
  # `BigFixActioner` creates an action from the imported BigFix Content
  #   The action is an offer that requires user interaction to run in self service application
  #   The action targets all computers whose name contains `autopkg`
  - Processor: com.github.jgstew.SharedProcessors/BigFixActioner

  - Processor: com.github.jgstew.SharedProcessors/TemplateDictionaryAppend
    Arguments:
      append_key: "patch"
      append_value: True

  - Processor: com.github.jgstew.SharedProcessors/ContentFromTemplate
    Arguments:
      # template_file_path: "%template_file_path%"
      content_file_pathname: "%RECIPE_CACHE_DIR%/%NAME%-Update.bes"

  - Processor: com.github.jgstew.SharedProcessors/BESImport
